#!/bin/zsh
# 4分割
# tmux split-window -v -p 30
# tmux split-window -h -p 50
# tmux split-window -h -p 50

# tmux split-window -v -p 30
# tmux split-window -h -p 50
# tmux select-pane -t 0
# tmux split-window -h -p 40

tmux split-window -h -p 50
tmux split-window -v -p 50
